SELECT COUNT(J.JP_ID) AS JOB_COUNT FROM [dbo].[DBO_JOBPOSTINGS] AS J
	LEFT JOIN [dbo].[DBO_]
WHERE J.PostingDate BETWEEN '2023-01-01' AND '2023-12-31'
AND J.VERIFIED = 1 AND J.Drafted = 0 AND J.Closed = 0
GROUP BY MONTH(J.PostingDate)