SELECT COUNT(DISTINCT ApplyId) FROM bdjCorporate..DBO_JOB_INBOX WHERE JP_ID = 1193224                -- 1018


-- Cross Check

SELECT P_ID,
ROW_NUMBER() OVER(PARTITION BY P_ID ORDER BY ApplyId DESC) AS r
FROM bdjCorporate..DBO_JOB_INBOX WHERE JP_ID = 1193224   