SELECT TOP (1000) [SrcID]
      ,[JP_ID]
      ,[P_ID]
      ,[ApplyDate]
      ,[SourceName]
  FROM [bdjCorporate].[rp].[ApplyFromOtherSrc]




SELECT TOP (1000) [JP_ID]
      ,[CP_ID]
      ,[JobTitle]
      ,[JobTitleBng]
      ,[AdType]
      ,[JobType]
      ,[ShowAliasName]
      ,[OnlineJob]
      ,[MinExp]
      ,[MaxExp]
      ,[MinAge]
      ,[MaxAge]
      ,[Sex]
      ,[PublishDate]
      ,[DeadLine]
      ,[Org_Type_ID]
      ,[ORG_TYPE_NAME_ENG]
      ,[ORG_TYPE_NAME_BNG]
      ,[ScannedFileName]
      ,[JobLang]
      ,[CompanyName]
      ,[CompanyNameBng]
      ,[LogoName]
      ,[OwnerOrgType]
      ,[HideCompanyAddress]
      ,[JobLevel]
      ,[RetiredArmy]
      ,[BlueCollar]
      ,[HideCompanyBusiness]
      ,[Vacancies]
      ,[SkillType]
      ,[TotalVacancy]
      ,[PremiumStartOn]
      ,[CatID]
      ,[CAT_NAME_ENG]
      ,[CAT_NAME_BNG]
      ,[AcademicQualificationEng]
      ,[AcademicQualificationBng]
      ,[KeyPointsEng]
      ,[KeyPointsBng]
      ,[DescriptionEng]
      ,[DescriptionBng]
      ,[ContextEng]
      ,[ContextBng]
      ,[RequirementsEng]
      ,[RequirementsBng]
      ,[LocationID]
      ,[L_Name_Eng]
      ,[L_Name_Bng]
      ,[L_TYPE_Eng]
      ,[OutsideBangladesh]
      ,[SourceID]
      ,[Source_Name_Eng]
      ,[Source_Name_Bng]
      ,[ORG_TYPES]
      ,[WORK_AREAS]
      ,[IndustryID]
      ,[IndustryNameEng]
      ,[IndustryNameBng]
      ,[PremiumJob]
      ,[AllowedPWD]
      ,[WorkPlace]
      ,[IsFacilityPWD]
      ,[PostedOn]
      ,[Fresher]
      ,[PriorityNumber]
  FROM [bdjActiveJobs].[dbo].[DBO_JOBPOSTINGS_ALL_AJ]

