SELECT TOP 5 * FROM [dbo].[UserSummary]
SELECT TOP 5 * FROM [bdjCorporate].[dbo].[DBO_JOB_INBOX]

SELECT TOP 20 
i.JP_ID, 
DATEDIFF(YEAR, 0, DATEADD(MONTH, s.TExp, 0)) AS Experience
FROM [bdjResumes].[dbo].[UserSummary] AS s
INNER JOIN [dbo].[DBO_JOB_INBOX] AS i ON i.P_ID = s.P_ID
INNER JOIN [dbo].[DBO_JOBPOSTINGS] AS j ON j.JP_ID = i.JP_ID
WHERE j.PublishDate >= '05-01-2023 00:00:00' AND j.PublishDate <= '12-31-2023 00:00:00' 
ORDER BY i.ApplyID DESC

;WITH USER_CTE AS (    SELECT DISTINCT CP_ID, JP_ID    --FROM bdjCorporate..DBO_JOBPOSTINGS	FROM arcCorporate..DBO_JOBPOSTINGS_arc    WHERE VERIFIED = 1 AND (CAT_ID >= 60 OR CAT_ID = -11)	UNION	 SELECT DISTINCT CP_ID, JP_ID    FROM bdjCorporate..DBO_JOBPOSTINGS	--FROM arcCorporate..DBO_JOBPOSTINGS_arc    WHERE VERIFIED = 1 AND (CAT_ID >= 60 OR CAT_ID = -11)), P_ID_CTE AS(	select  DISTINCT  i.P_ID, COUNT(I.APPLYID) AS [Total job application],	    COUNT(CASE WHEN i.P_DATE >= DATEADD(MONTH, -6, GETDATE()) THEN i.APPLYID END) AS count_last_6_months	from DBO_JOB_INBOX i	INNER JOIN USER_CTE u on i.JP_ID = u.JP_ID	GROUP BY i.P_ID	UNION	SELECT DISTINCT  i.P_ID,COUNT(I.APPLYID) AS [Total job application], COUNT(CASE WHEN i.P_DATE >= DATEADD(MONTH, -6, GETDATE()) THEN i.APPLYID END) AS count_last_6_months	FROM arcCorporate..DBO_JOB_INBOX_arc i	INNER JOIN USER_CTE u on i.JP_ID = u.JP_ID	GROUP BY i.P_ID),ID AS(	select P.ID	,p.PhotoUploaded	from bdjResumes..PERSONAL p	INNER JOIN P_ID_CTE  pc on p.ID = pc.P_ID	GROUP BY P.ID,p.PhotoUploaded,p.NAME,p.MOBILE,CONCAT(DATEDIFF(year, p.BIRTH, GETDATE()), '.', DATEDIFF(month, p.BIRTH, GETDATE()) % 12),	CASE WHEN p.M_STATUS = 0 THEN 'UnMarried' ELSE 'Married' END),CV_CTE AS (	Select  P.ID,case when p.PhotoUploaded =  1 then 20 end as photo, 		E=case when (select top 1 ed_id from bdjResumes..Edu where P_ID=p.ID) > 0 then 20 end, T=case when (select top 1 t_id from bdjResumes..TRAINING where P_ID=p.ID) > 0 then 5 end, 		P=case when (select top 1 pe_id from bdjResumes..PEdu where P_ID=p.ID) > 0 then 5 end , X= case when (select top 1 ex_id from bdjResumes..[EXP] where P_ID=p.ID) > 0 then 20 end,		S=case when (select top 1 p_id from bdjResumes..SPECIALIST where P_ID=p.ID) > 0 then 5 end, 		R=case when (select top 1 r_id from bdjResumes..REF where P_ID=p.ID) > 0 then 5 end,		case when ac.CVPosted = 1 then 20 end personal, ac.accCatId AS CAT_ID	From ID  p	Left Join bdjResumes..PersonalExtras pe on p.Id=pe.p_id	LEFT Join bdjResumes..useraccounts ac on p.id=ac.accid	)	SELECT N.ID	,(CASE WHEN photo IS NULL THEN 0 ELSE photo END)+(CASE WHEN E IS NULL THEN 0 ELSE E END)+(CASE WHEN T IS NULL THEN 0 ELSE T END)+(CASE WHEN P IS NULL THEN 0 ELSE P END) +(CASE WHEN X IS NULL THEN 0 ELSE X END)  +(CASE WHEN S IS NULL THEN 0 ELSE S END)+(CASE WHEN R IS NULL THEN 0 ELSE R END)+(CASE WHEN personal IS NULL THEN 0 ELSE personal END)  as [Bdjobs profile completeness]	from CV_CTE N	LEFT JOIN bdjResumes.vdo.VideoResumes V ON N.ID = V.P_ID